name: Industrialisation continue sur le serveur Alwaysdata
on: push
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Define the target directory
            TARGET_DIR=$HOME/www/esat2
            REPO_NAME=$(basename ${{ github.repository }})

            # Navigate to the target directory
            cd $TARGET_DIR

            # Check if the repository directory exists and is not empty
            if [ -d "$REPO_NAME/.git" ]; then
              # Repository exists, pull the latest changes
              cd $REPO_NAME
              git pull
            else
              # Repository does not exist, clone it
              git clone https://github.com/${{ github.repository }}.git
              cd $REPO_NAME
            fi

            # Ensure the Flask directory exists
            if [ ! -d "./flask" ]; then
              mkdir flask
            fi
            
            # Sync files to the Flask directory
            rsync -r ./ ./flask

  Restart:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Restart Alwaysdata site
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST --basic --user "${{ secrets.ALWAYSDATA_TOKEN }}:" https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_SITE_ID }}/restart/)
          if [ "$response_code" -eq 204 ]; then
            echo "Relance de votre site réussi"
          elif [ "$response_code" -eq 404 ]; then
            echo "Vous n'avez pas renseigner correctement votre secret ALWAYSDATA_SITE_ID"
            exit 1  # Quitter avec un code d'erreur
          elif [ "$response_code" -eq 401 ]; then
            echo "Vous n'avez pas renseigner correctement votre secret ALWAYSDATA_TOKEN"
            exit 1  # Quitter avec un code d'erreur
          else
            echo "Échec du redémarrage avec le code de réponse : $response_code"
            exit 1  # Quitter avec un code d'erreur
          fi
