name: Industrialisation continue sur le serveur Alwaysdata
on: push
jobs:
  Prepare-and-Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This action checks out your repository under $GITHUB_WORKSPACE

      - name: Setup SSH and Sync files
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Ensure the target directory exists
            if [ ! -d "$HOME/www/esat1" ]; then
              echo "The target directory does not exist"
              exit 1  # Exit if target directory does not exist
            fi

            # Sync repository files to the target directory
            rsync -avz --delete $GITHUB_WORKSPACE/ $HOME/www/esat1/

  Restart:
    needs: Prepare-and-Sync
    runs-on: ubuntu-latest
    steps:
      - name: Restart Alwaysdata site
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST --basic --user "${{ secrets.ALWAYSDATA_TOKEN }}:" https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_SITE_ID }}/restart/)
          if [ "$response_code" -eq 204 ]; then
            echo "Site restart successful"
          elif [ "$response_code" -eq 404 ]; then
            echo "ALWAYSDATA_SITE_ID not correctly set"
            exit 1  # Exit with error code
          elif [ "$response_code" -eq 401 ]; then
            echo "ALWAYSDATA_TOKEN not correctly set"
            exit 1  # Exit with error code
          else
            echo "Site restart failed with response code: $response_code"
            exit 1  # Exit with error code
